In [15]:
# Dummy Var & OneHotEncoding-28-12-18

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


#------------------------------------------

# Check the price for 2700 and 3400 sqft area in Mumbai

In [16]:
df = pd.read_csv('E:/ML/Housep1.csv')
df.head()

City  Area  Price
0  londan  2500  30000
1  londan  3000  40000
2  londan  3200  20000
3  londan  3600  35000
4  londan  4000  55000

In [17]:
# add the dummy variables in dataset as below, for the City column
dummy=pd.get_dummies(df.City)

In [18]:
dummy

Chicago  Mumbai  londan
0         0       0       1
1         0       0       1
2         0       0       1
3         0       0       1
4         0       0       1
5         1       0       0
6         1       0       0
7         1       0       0
8         1       0       0
9         0       1       0
10        0       1       0
11        0       1       0
12        0       1       0

In [19]:
# Merged the Df and dummy dataset as below
merged = pd.concat([df, dummy], axis='columns')

In [20]:
merged

City  Area   Price  Chicago  Mumbai  londan
0    londan  2500   30000        0       0       1
1    londan  3000   40000        0       0       1
2    londan  3200   20000        0       0       1
3    londan  3600   35000        0       0       1
4    londan  4000   55000        0       0       1
5   Chicago  2600  750000        1       0       0
6   Chicago  2800  615000        1       0       0
7   Chicago  3300  650000        1       0       0
8   Chicago  3600  710000        1       0       0
9    Mumbai  2600  575000        0       1       0
10   Mumbai  2900  600000        0       1       0
11   Mumbai  3100  620000        0       1       0
12   Mumbai  3200  690000        0       1       0

In [21]:
# Drop the columns from dataset as below

final = merged.drop(['City','londan'], axis='columns')

In [22]:
final

Area   Price  Chicago  Mumbai
0   2500   30000        0       0
1   3000   40000        0       0
2   3200   20000        0       0
3   3600   35000        0       0
4   4000   55000        0       0
5   2600  750000        1       0
6   2800  615000        1       0
7   3300  650000        1       0
8   3600  710000        1       0
9   2600  575000        0       1
10  2900  600000        0       1
11  3100  620000        0       1
12  3200  690000        0       1

In [24]:
# Create the model

model = LinearRegression()

In [28]:
# get the fetures variable

x = final.drop(['Price'], axis='columns')
x

Area  Chicago  Mumbai
0   2500        0       0
1   3000        0       0
2   3200        0       0
3   3600        0       0
4   4000        0       0
5   2600        1       0
6   2800        1       0
7   3300        1       0
8   3600        1       0
9   2600        0       1
10  2900        0       1
11  3100        0       1
12  3200        0       1

In [29]:
y = final.Price
y

0      30000
1      40000
2      20000
3      35000
4      55000
5     750000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    690000
Name: Price, dtype: int64

In [30]:
# Train your data
model.fit(x,y)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [36]:
# check the price for 2700 sqft in mumbai
model.predict([[2700,0,1]])

array([615891.19562691])

In [37]:
# check the price for 3400 sqft in mumbai
model.predict([[3400,1,0]])

array([688216.44568503])

In [38]:
model.score(x,y)

0.9849516920680288

In [68]:
# One hot encoding


df.head()

City  Area  Price
0     2  2500  30000
1     2  3000  40000
2     2  3200  20000
3     2  3600  35000
4     2  4000  55000

In [69]:
# do the Label endcoded

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [70]:
dfle = df
dfle.City = le.fit_transform(dfle.City)

In [71]:
dfle

City  Area   Price
0      2  2500   30000
1      2  3000   40000
2      2  3200   20000
3      2  3600   35000
4      2  4000   55000
5      0  2600  750000
6      0  2800  615000
7      0  3300  650000
8      0  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3200  690000

In [58]:
# Define the x and y variables

x =dfle[['City','Area']].values
x

array([[   2, 2500],
       [   2, 3000],
       [   2, 3200],
       [   2, 3600],
       [   2, 4000],
       [   0, 2600],
       [   0, 2800],
       [   0, 3300],
       [   0, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3200]], dtype=int64)

In [59]:
y=dfle.Price
y

0      30000
1      40000
2      20000
3      35000
4      55000
5     750000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    690000
Name: Price, dtype: int64

In [72]:
# train your data that is fit

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])


x = ohe.fit_transform(x).toarray()
x

array([[1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 2.5e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 3.2e+03]])

In [74]:
x = x[:,1:]
x

array([[0.0e+00, 1.0e+00, 2.5e+03],
       [0.0e+00, 1.0e+00, 3.0e+03],
       [0.0e+00, 1.0e+00, 3.2e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.2e+03]])

In [75]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [76]:
model.predict([[0,1,2700]])

array([23996.2782042])

In [80]:
# check the price for 3400 sqft in mumbai

model.predict([[0,0,3400]])

array([688216.44568507])