In [8]:
# Pickle & Joblib for LinesrRegression-28-12-18
# import pythons library

import pandas as pd
import numpy as np
from sklearn import linear_model
#from sklearn.datasets import fetch_20newsgroups


# Find the price of 5000 and 4500 Sqft area 

In [9]:
# Read the dataset
df = pd.read_csv('E:/ML/Housep.csv')
df

Area   Price
0  2500   30000
1  3000   40000
2  3200   20000
3  3600   35000
4  4000   55000
5  4100  750000

In [12]:
# Use the linear regression model
model = linear_model.LinearRegression()
model.fit(df[['Area']], df.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
# get coeficient
model.coef_

array([272.63157895])

In [14]:
# get the intercept
model.intercept_

-771947.3684210529

In [16]:
# check the price of 5000 sqft area
model.predict(5000)

array([591210.52631579])

In [32]:
# check the price of 4500 sqft area
model.predict(4500)

array([454894.73684211])

In [18]:
# check the price by using pickle model and joblib
import pickle

In [19]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model,f)

In [20]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [21]:
mp.predict(5000)

array([591210.52631579])

In [26]:
# joblib
from sklearn.externals import joblib

joblib.dump(model, 'model_joblib')

['model_joblib']

In [29]:
mj = joblib.load('model_joblib')
mj.predict(5000)

array([591210.52631579])

In [30]:
mj.coef_

array([272.63157895])

In [31]:
mj.intercept_

-771947.3684210529